import type { Product, Reward, Tier, LiveTickerItem } from './types';

export const CAMPAIGN_ID = 'NNC_B2B_REWARDS_Q3_2026';
export const CAMPAIGN_PERIOD = '01/08 – 30/09/2026';
export const WHATSAPP_NUMBER = '8562095355355';
export const SHEET_WEBHOOK_URL = '';

export const PRODUCTS: Product[] = [
  {
    id: 'tadimax',
    name: 'Tadimax',
    image: '/images/tadimax.webp',
    packVi: 'Hộp 21 viên × 2 vỉ',
    packLo: 'ກັບ 21 ເມັດ × 2 ແຜງ',
    priceKip: 193000,
    formulation: 'Cao khô Trinh nữ hoàng cung 250mg, Hoàng cầm 110mg, Hoàng kỳ 110mg',
    descriptionVi: 'Hỗ trợ điều trị phì đại lành tính tuyến tiền liệt và u xơ tử cung. Sản phẩm thảo dược chủ lực uy tín của NNC.',
    descriptionLo: 'ຊ່ວຍປິ່ນປົວຕ່ອມລູກໝາກໃຫຍ່ ແລະ ອຸມລູກ. ຜະລິດຕະພັນສົມບູນແບບຈາກ NNC.',
    categoryVi: 'Thảo dược kỹ thuật cao',
    categoryLo: 'ສະໝຸນໄພເຕັກໂນໂລຊີສູງ',
    isFlagship: true,
  },
  {
    id: 'bai-thach',
    name: 'Bài Thạch',
    image: '/images/bai-thach.webp',
    packVi: 'Hộp 45 viên',
    packLo: 'ກັບ 45 ເມັດ',
    priceKip: 69000,
    formulation: 'Kim tiền thảo 1000mg, Râu mèo 250mg, Thạch vĩ, Hạt chuối hột',
    descriptionVi: 'Hỗ trợ bài sỏi đường tiết niệu, sỏi thận, sỏi mật. Giảm viêm và lợi tiểu tự nhiên.',
    descriptionLo: 'ຊ່ວຍຂັບນິ້ວໃນທາງເດີນປັດສະວະ, ນິ້ວໄຂ່ຫຼັງ. ຫຼຸດການອັກເສບ.',
    categoryVi: 'Thảo dược bài sỏi',
    categoryLo: 'ສະໝຸນໄພຂັບນິ້ວ',
    isFlagship: true,
  },
  {
    id: 'cv-mox-1000',
    name: 'CV Mox 1000',
    image: '/images/cvmox-1000.webp',
    packVi: 'Hộp 2 vỉ × 7 viên',
    packLo: 'ກັບ 2 ແຜງ × 7 ເມັດ',
    priceKip: 71000,
    formulation: 'Amoxicillin 875mg + Acid Clavulanic 125mg',
    descriptionVi: 'Kháng sinh phối hợp phổ rộng thế hệ mới, điều trị nhiễm khuẩn hô hấp, tai mũi họng, tiết niệu nặng.',
    descriptionLo: 'ຢາຕ້ານເຊື້ອປະສົມປະສານ, ປິ່ນປົວການຕິດເຊື້ອທາງເດີນຫາຍໃຈ.',
    categoryVi: 'Kháng sinh kê đơn cao cấp',
    categoryLo: 'ຢາຕ້ານເຊື້ອພິເສດ',
    isFlagship: true,
  },
  {
    id: 'nc-cv-mox-625',
    name: 'NC CV Mox 625',
    image: '/images/nc-cvmox-625.webp',
    packVi: 'Hộp 10 vỉ × 10 viên',
    packLo: 'ກັບ 10 ແຜງ × 10 ເມັດ',
    priceKip: 369000,
    formulation: 'Amoxicillin 500mg + Acid Clavulanic 125mg',
    descriptionVi: 'Hộp lớn 100 viên tiết kiệm cho phòng khám & quầy thuốc kê đơn thường quy.',
    descriptionLo: 'ກ່ອງໃຫຍ່ 100 ເມັດ ປະຢັດສຳລັບຄລີນິກ.',
    categoryVi: 'Kháng sinh kê đơn',
    categoryLo: 'ຢາຕ້ານເຊື້ອ',
    isFlagship: false,
  },
  {
    id: 'cv-mox-228-5',
    name: 'CV Mox 228.5',
    image: '/images/cvmok-228.webp',
    packVi: 'Chai 60 ml siro',
    packLo: 'ຕຸກ 60 ml ສີໂຣ',
    priceKip: 24000,
    formulation: 'Amoxicillin 200mg + Acid Clavulanic 28.5mg / 5ml',
    descriptionVi: 'Káng sinh dạng siro vị ngọt dễ uống dành riêng cho bệnh nhi.',
    descriptionLo: 'ຢາຕ້ານເຊື້ອສີໂຣຫວານງ່າຍສຳລັບເດັກນ້ອຍ.',
    categoryVi: 'Kháng sinh Nhi khoa',
    categoryLo: 'ຢາຕ້ານເຊື້ອເດັກນ້ອຍ',
    isFlagship: false,
  },
  {
    id: 'cefixad-100',
    name: 'Cefixad 100mg',
    image: '/images/cefixad-100.webp',
    packVi: 'Chai 30 ml hỗn dịch',
    packLo: 'ຕຸກ 30 ml',
    priceKip: 30000,
    formulation: 'Cefixime 100mg / 5ml',
    descriptionVi: 'Kháng sinh Cephalosporin thế hệ 3 dạng hỗn dịch uống cho trẻ em.',
    descriptionLo: 'ຢາຕ້ານເຊື້ອ Cephalosporin ຂັ້ນ 3 针对ເດັກນ້ອຍ.',
    categoryVi: 'Kháng sinh Nhi khoa',
    categoryLo: 'ຢາຕ້ານເຊື້ອເດັກນ້ອຍ',
    isFlagship: false,
  },
  {
    id: 'azihadi',
    name: 'AZIHADI',
    image: '/images/azihadi.webp',
    packVi: 'Chai 30 ml hỗn dịch',
    packLo: 'ຕຸກ 30 ml',
    priceKip: 32000,
    formulation: 'Azithromycin 200mg / 5ml',
    descriptionVi: 'Kháng sinh Macrolide liều 1 lần/ngày tiện lợi trong viêm hô hấp nhi khoa.',
    descriptionLo: 'ຢາຕ້ານເຊື້ອ Macrolide 1 ຢ່າງ/ມື້.',
    categoryVi: 'Kháng sinh Nhi khoa',
    categoryLo: 'ຢາຕ້ານເຊື້ອເດັກນ້ອຍ',
    isFlagship: false,
  },
];

export const TIERS: Tier[] = [
  {
    id: 'tier-1',
    nameVi: 'Bậc 1',
    nameLo: 'ຂັ້ນ 1',
    minRevenueKip: 2000000,
    maxRevenueKip: 6000000,
    immediateDiscountPercent: 5,
    quarterRewardPercent: 2,
    totalBenefitPercent: 7,
    giftValueKip: 420000,
  },
  {
    id: 'tier-2',
    nameVi: 'Bậc 2',
    nameLo: 'ຂັ້ນ 2',
    minRevenueKip: 6000000,
    maxRevenueKip: 12000000,
    immediateDiscountPercent: 5,
    quarterRewardPercent: 3,
    totalBenefitPercent: 8,
    giftValueKip: 960000,
  },
  {
    id: 'tier-3',
    nameVi: 'Bậc 3',
    nameLo: 'ຂັ້ນ 3',
    minRevenueKip: 12000000,
    maxRevenueKip: 25000000,
    immediateDiscountPercent: 5,
    quarterRewardPercent: 4,
    totalBenefitPercent: 9,
    giftValueKip: 2250000,
  },
  {
    id: 'tier-4',
    nameVi: 'Bậc 4',
    nameLo: 'ຂັ້ນ 4',
    minRevenueKip: 25000000,
    maxRevenueKip: null,
    immediateDiscountPercent: 5,
    quarterRewardPercent: 5,
    totalBenefitPercent: 10,
    giftValueKip: null,
  },
];

export const REWARDS: Reward[] = [
  {
    id: 'office-kit',
    nameVi: 'Bộ quà văn phòng NNC (Sổ + Bút + Ô cao cấp)',
    nameLo: 'ເຄື່ອງໃຊ້ຫ້ອງການ NNC (ປຶ້ມ + ບິກ + ຮົ່ມ)',
    shortVi: 'Bộ quà văn phòng',
    shortLo: 'ເຄື່ອງໃຊ້ຫ້ອງການ',
    weight: 25,
    status: 'active',
    wheelIndex: 0,
    conditionVi: 'Áp dụng cho mọi đơn hàng',
    conditionLo: 'ໃຊ້ໄດ້ກັບທຸກໆບິນ',
  },
  {
    id: 'voucher-100k',
    nameVi: 'Voucher giảm 100.000 KIP',
    nameLo: 'Voucher ຫຼຸດ 100.000 KIP',
    shortVi: 'Voucher 100.000 KIP',
    shortLo: 'Voucher 100K',
    weight: 22,
    status: 'active',
    wheelIndex: 1,
    conditionVi: 'Áp dụng đơn sỉ từ 2.000.000 KIP',
    conditionLo: 'ໃຊ້ກັບບິນ 2.000.000 KIP',
  },
  {
    id: 'free-ship-2',
    nameVi: 'Miễn phí vận chuyển 2 đơn đầu tiên',
    nameLo: 'ຟຣີຄ່າສົ່ງ 2 ບິນທຳອິດ',
    shortVi: 'Freeship 2 đơn',
    shortLo: 'ຟຣີຄ່າສົ່ງ 2 ບິນ',
    weight: 20,
    status: 'active',
    wheelIndex: 2,
    conditionVi: 'Áp dụng toàn quốc Lào',
    conditionLo: 'ໃຊ້ໄດ້ທົ່ວປະເທດລາວ',
  },
  {
    id: 'gift-tadimax',
    nameVi: 'Tặng 1 hộp Tadimax cao cấp',
    nameLo: 'ແຖມ 1 ກັບ Tadimax',
    shortVi: '1 Hộp Tadimax',
    shortLo: '1 ກັບ Tadimax',
    weight: 15,
    status: 'active',
    wheelIndex: 3,
    conditionVi: 'Áp dụng đơn sỉ từ 3.000.000 KIP',
    conditionLo: 'ໃຊ້ກັບບິນ 3.000.000 KIP',
  },
  {
    id: 'extra-1-percent',
    nameVi: 'Chiết khấu thêm 1% đơn đầu tiên',
    nameLo: 'ຫຼຸດເພີ່ມ 1% ບິນທຳອິດ',
    shortVi: 'Chiết khấu thêm 1%',
    shortLo: 'ຫຼຸດເພີ່ມ 1%',
    weight: 12,
    status: 'active',
    wheelIndex: 4,
    conditionVi: 'Tối đa 300.000 KIP',
    conditionLo: 'ສູງສຸດ 300.000 KIP',
  },
  {
    id: 'voucher-200k',
    nameVi: 'Voucher giảm 200.000 KIP',
    nameLo: 'Voucher ຫຼຸດ 200.000 KIP',
    shortVi: 'Voucher 200.000 KIP',
    shortLo: 'Voucher 200K',
    weight: 6,
    status: 'active',
    wheelIndex: 5,
    conditionVi: 'Áp dụng đơn sỉ từ 5.000.000 KIP',
    conditionLo: 'ໃຊ້ກັບບິນ 5.000.000 KIP',
  },
];

export const ACTIVE_REWARDS = REWARDS.filter((r) => r.status === 'active');

export const LIVE_TICKER_DATA: LiveTickerItem[] = [
  {
    id: 'ticker-1',
    name: 'Nhà thuốc Vang Vieng',
    business: 'Nhà thuốc',
    province: 'Vientiane',
    rewardVi: 'vừa trúng Bộ quà văn phòng NNC',
    rewardLo: 'ໄດ້ຮັບ ເຄື່ອງໃຊ້ຫ້ອງການ NNC',
    timeAgoVi: '2 phút trước',
    timeAgoLo: '2 ນາທີກ່ອນ',
  },
  {
    id: 'ticker-2',
    name: 'Phòng khám Champasak',
    business: 'Phòng khám',
    province: 'Champasak',
    rewardVi: 'vừa mở khóa Thưởng tích lũy Bậc 3 (9%)',
    rewardLo: 'ເປີດສິດໂບນັດ ຂັ້ນ 3 (9%)',
    timeAgoVi: '5 phút trước',
    timeAgoLo: '5 ນາທີກ່ອນ',
  },
  {
    id: 'ticker-3',
    name: 'Nhà thuốc Savannakhet',
    business: 'Nhà thuốc',
    province: 'Savannakhet',
    rewardVi: 'vừa nhận Voucher 200.000 KIP',
    rewardLo: 'ໄດ້ຮັບ Voucher 200.000 KIP',
    timeAgoVi: '12 phút trước',
    timeAgoLo: '12 ນາທີກ່ອນ',
  },
  {
    id: 'ticker-4',
    name: 'Bác sĩ Bounmy',
    business: 'Phòng khám',
    province: 'Luang Prabang',
    rewardVi: 'vừa đăng ký mở lượt quay tri ân',
    rewardLo: 'ໄດ້ລົງທະບຽນເປີດສິດໝູນ',
    timeAgoVi: '18 phút trước',
    timeAgoLo: '18 ນາທີກ່ອນ',
  },
  {
    id: 'ticker-5',
    name: 'Nhà thuốc Pakse Central',
    business: 'Nhà thuốc',
    province: 'Champasak',
    rewardVi: 'vừa trúng 1 Hộp Tadimax',
    rewardLo: 'ໄດ້ຮັບ 1 ກັບ Tadimax',
    timeAgoVi: '25 phút trước',
    timeAgoLo: '25 ນາທີກ່ອນ',
  },
];
